# chromosome nubmer you are workign with (important for writing the bed file to annotate the vcf)
chr_number: 5
# name of the vcf file you provide to run the simulation on 
base_vcf: 'chr5_grenenet.vcf'
# base fasta file used by slim 
base_fasta: 'chr5.fasta'
# proportion of contributin snps to the trait
pi: [0.001,0.01]
# standard deviation of effect sizes of contributing loci 
beta: [5,6]
# ecotypes randomly selected from a temperature gradient to represent the optimum values in each environment 
optimum_ecotypes: 'optimum_ecotypes.csv'
# number of replicates of each simulation to run
replicates: 12
# number of different environments to simulate
optima: 32
# inital population size in the simulation 
initial_pop: 10800